/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StringCalculator;

public class App {
    public static void main(String[] args) {
        StringCalculator stringCalculator = new StringCalculator();
        System.out.println(stringCalculator.Add(args[0]));
    }
}
